[package]
name = "proactive_refresh"
version = "0.1.0"
edition = "2021"

[dependencies]
ff-zeroize = "0.6.3"
pairing-plus = "0.19"
serde_json = "1.0.93"

[dependencies.curv]
git = "https://github.com/ZenGo-X/curv"
tag = "v0.6.2"
default-features = false

[features]
default = ["curv/rust-gmp-kzen"]
